### ISSUE TITLE
Multicast behaviour

### ISSUE THREAD

**Issue by brucou** [mostjs/create#13]
This is more of a question than an issue.

> Note that the publisher will not be called until there is demand for the stream's events. Specifically, the publisher will be called when the number of observers goes from zero to one.

My question is what happens when the number of observers goes from one to two. Is the publisher called anew? Or alternatively the publisher is not called and the new observer will only receive values produced after its subscription?

**Comment by TylorS** [comment]
Hello @brucou, `create()` is automatically multicasted as you can see [here](https://github.com/mostjs/create/blob/master/src/index.js#L8) in the source code, where we make use of `MulticastSource`. So the publisher will not be called again on subsequent observers and will simply receive values produced after the time of subscription.
